server:
  port: 8081

com:
  xwxcloud:
#    file:
#      enable: false
#      xxx: yyy
    portal:
      enable: false
      xxx: yyy
    auth:
      enable: true
      xxx: yyy

logging:
  level:
    root: info
    com.baomidou.mybatisplus: DEBUG
    com.yueny.demo: DEBUG
